  version: "3"

  services:
    mysqldb1:
      container_name: mysqldb1
      image: mysql:8
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: root
  #    volumes:
   #     - /home/mysql/data:/var/lib/mysql

    spring_app:
      image: abdelwehed/achat
      container_name: achatproject1
      restart: on-failure
      ports:
        - 8089:9001
      depends_on:
        - mysqldb1
